# Generated by Django 4.1.3 on 2023-04-08 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='React',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.TextField()),
                ('summary', models.TextField()),
                ('contentURL', models.URLField()),
                ('imageURL', models.URLField()),
            ],
        ),
    ]
